server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3406/study_example
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true
  main:
    web-application-type: servlet